import { createElement } from 'lwc';
import Lwc_ComboBox_with_Imperative_Method_with_Child_Records from 'c/lwc_ComboBox_with_Imperative_Method_with_Child_Records';

describe('c-lwc-combo-box-with-imperative-method-with-child-records', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-combo-box-with-imperative-method-with-child-records', {
            is: Lwc_ComboBox_with_Imperative_Method_with_Child_Records
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});